name: Sync upstream (every 30 min)

on:
  schedule: # cron UTC
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Fast-forward main from upstream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sSLf -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/merge-upstream \
            -d '{"branch":"main"}'
